### ISSUE TITLE
MIUI13，lsp框架无效

### ISSUE THREAD

**Issue by eosed** [Xposed-Modules-Repo/io.github.tehcneko.undo#1]
实测模块在MIUI13开发内测版上是无效的，lsp上1.8版本，勾选作用域是选的系统框架，不知道是不是。

**Comment by MWTJC** [comment]
同上，但miui12.5，也不清楚在lsp环境下的生效条件

**Comment by tehcneko** [comment]
需要勾选生效应用

**Comment by eosed** [comment]
逻辑有问题吧，既然勾选了系统框架，不应该是全局吗？其次是tim上也有问题
![Uploading Screenshot_2022-06-06-00-19-58-883-edit_com.tencent.tim.jpg…]()

**Comment by tehcneko** [comment]
谁告诉你勾了系统框架就是全局的？
